import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
  

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next UI",
  description: "Generated by create next app",
   themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en" className="bg-black" suppressHydrationWarning>
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-white  antialiased`}
      >
        <ThemeProvider
        attribute={"class"}
        defaultTheme="black"
        enableSystem={false}
        >
        <main>
        {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}


