import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavWrapper from "@/components/wrapper/NavWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import LenisScroller from "@/lib/LenisScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"suppressHydrationWarning >
      <body 
      
      className={`${geistSans.variable}  transition-all duration-1000 ease-in-out dark:bg-["#171717"] bg-neutral-400 ${geistMono.variable} antialiased`}
      >
        <LenisScroller>

        <ThemeProvider
           attribute="class"
           defaultTheme="system"
           enableSystem
           >
          <NavWrapper>
            {children}
          </NavWrapper>
        </ThemeProvider>
      </LenisScroller>
      </body>
    </html>
  );
}
